### ISSUE TITLE
Open source license request

### ISSUE THREAD

**Issue by michaelbgd** [darvld/ux#1]
Please consider adding an open source license such as Apache 2.0 or MIT to this project.

Thanks for the nice work!

**Comment by darvld** [comment]
Done! I actually had added one, but then I changed the repository so I could start with a cleaner structure and the license file was lost. Thanks for the reminder!

**Comment by michaelbgd** [comment]
Thanks.

Please be aware that placing your project under the GPL-3.0 will effectively make it unusable for commercial purposes.
